#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルについては https://github.com/sevenc-nanashi/aviutl2-cli を参照してください。
[project]
id = "color-halftone"
name = "AviUtl2-ColorHalftone"
version = "1.1.0"

[artifacts.ColorHalftone_anm2]
build = "cd ./script && aulua build"
source = "./out_script/ColorHalftone.anm2"
destination = "Script/ColorHalftone.anm2"

[artifacts.English_ColorHalftone_aul2]
source = "./translations/English.ColorHalftone.aul2"
destination = "Language/English.ColorHalftone.aul2"

[development]
aviutl2_version = "latest"

[preview]

[release]
package_template = "package.txt"
output_dir = "release"
zip_name = "{name}-v{version}"
include = ["ColorHalftone_anm2", "English_ColorHalftone_aul2"]
